apiVersion: v1
kind: ConfigMap
metadata:
  name: load-generator
data:
  # Number of logs to generate per second
  eventsPerSecond: "2"
  # Total number of logs to generate
  iterations: "100"
  # Percentage of large logs to generate (0: 100% small logs, 50: 50% large logs, etc.)
  percentLargeBuffer: "0"
  # Size of small logs in bytes
  smallBufferSizeBytes: "100"
  # Size of large logs in bytes
  largeBufferSizeBytes: "20"

  load-generator.py: |
    #!/usr/bin/python3.9

    import string
    import random
    import time
    import math
    import sys
    import os
    import datetime
    import json

    smallBufferSizeBytes = int(os.environ.get('SMALL_BUFFER_SIZE_BYTES'))
    largeBufferSizeBytes = int(os.environ.get('LARGE_BUFFER_SIZE_BYTES'))
    proposedEventsPerSecond = int(os.environ.get('EVENTS_PER_SECOND'))
    iterations = int(os.environ.get('ITERATIONS'))
    percentLargeBuffer = int(os.environ.get('PERCENT_LARGE_BUFFER'))

    smallBuffer = ''.join(random.choice(string.ascii_letters+string.digits) for i in range(smallBufferSizeBytes))
    largeBuffer = ''.join(random.choice(string.ascii_letters+string.digits) for i in range(largeBufferSizeBytes))

    delaySeconds = float(1/proposedEventsPerSecond)

    for x in range(iterations):
        timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()

        if random.randint(0,100) < percentLargeBuffer:
            log_line = {
                "timestamp": timestamp,
                "iteration": x,
                "message": largeBuffer
            }

            print(json.dumps(log_line))
        else:
            log_line = {
                "timestamp": timestamp,
                "iteration": x,
                "message": smallBuffer
            }

            print(json.dumps(log_line))

        sys.stdout.flush()
        time.sleep(delaySeconds)

    while True:
      time.sleep(10)
